#!/bin/bash
#sudo su -c "rtcwake -m mem -s 10"
THIS_TERMINAL=$(xdotool getactivewindow) 
flatpak run eu.tiliado.NuvolaAppYandexMusic >/dev/null 2>&1 &
sleep 10
xdotool search --desktop 0 --name "Yandex" windowactivate --sync 
WINDOW_ID=$(xdotool getactivewindow) 
unset x y w h
  eval $(xwininfo -id $WINDOW_ID |
  sed -n -e "s/^ \+Absolute upper-left X: \+\([0-9]\+\).*/x=\1/p" \
         -e "s/^ \+Absolute upper-left Y: \+\([0-9]\+\).*/y=\1/p" \
         -e "s/^ \+Width: \+\([0-9]\+\).*/w=\1/p" \
         -e "s/^ \+Height: \+\([0-9]\+\).*/h=\1/p" )
xdotool mousemove $((x+w/2)) $((y+h/2)) click 1 key  space
notify-send "Good Morning, blyat"
xdotool windowactivate $THIS_TERMINAL  windowkill $THIS_TERMINAL  
 
#-t $(date -d '2019-03-01 10:00:00' +%s)

